### ISSUE TITLE
Initial Setup of FSM

### ISSUE THREAD

**Issue by kennethamackenzie** [petertufvesson/ha-fsm#3]
I am unsure as to where to put the FSM files and how to link them to my app.

I put the FSM files in the `/config/appdaemon/apps/` folder and added the following at the top of my app file:
`import appdaemon.plugins.hass.hassapi as hass`
`import fsm_fsm as Fsm`
`import fsm_state as State`
`import fsm_transition as Transition`
`import fsm_condition as Condition`

Which seemed to get the FSM classes available to my app; but generated a new issue.

`2022-06-09 12:18:13.503419 WARNING vpd_fsm: ------------------------------------------------------------`
`2022-06-09 12:18:13.508078 WARNING vpd_fsm: Unexpected error in worker for App vpd_fsm:`
`2022-06-09 12:18:13.508622 WARNING vpd_fsm: Worker Ags: {}`
`2022-06-09 12:18:13.511589 WARNING vpd_fsm: ------------------------------------------------------------`
`2022-06-09 12:18:13.522530 WARNING vpd_fsm: Traceback (most recent call last):`
`  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app`
`    await utils.run_in_executor(self, init)`
`  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor`
`    response = future.result()`
`  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run`
`    result = self.fn(*self.args, **self.kwargs)`
`  File "/config/appdaemon/apps/vpd_fsm.py", line 15, in initialize`
`    Condition(entity='sensor.t4_rh_too_high', operand='eq')`
`TypeError: 'module' object is not callable`
`2022-06-09 12:18:13.522790 WARNING vpd_fsm: ------------------------------------------------------------`
`2022-06-09 12:18:13.523087 INFO AppDaemon: App initialization complete`

Does this mean that the FSM is available to my app and that **my configuration needs work**?

Or does it mean that the **FSM still needs to be installed corrected**? And then **linked into my app correctly**?

Any assistance would be greatly appreciated. TIA.

**Comment by petertufvesson** [comment]
Hi Kenneth.

When you do this:
`Condition(entity='sensor.t4_rh_too_high', operand='eq')`

I think you have mixed up argument "operand" with "operator". Try this:
`Condition(entity='sensor.t4_rh_too_high', operator=Eq)`

Note: The operator argument refers to a class, so case is important and it should not be wrapped as a string. All valid classes are found in fsm_condition.py
I suspect you also want to have the "operand" argument present. Otherwise you will check the operand vs the default value "0".

Last I see the import needs to be changed a bit as well. Replace
`import fsm_condition as Condition`
with
`from fsm_condition import Condition, TRUE2, Eq, Neq, LE, GE, LT, GT`

Good luck!

**Comment by kennethamackenzie** [comment]
Hi Peter,

Thank you for your reply and guidance. 

I have made the code changes but I am getting a similar issue:
`2022-06-10 20:44:06.777121 WARNING vpd_fsm: ------------------------------------------------------------`
`2022-06-10 20:44:06.782299 WARNING vpd_fsm: Unexpected error in worker for App vpd_fsm:`
`2022-06-10 20:44:06.789243 WARNING vpd_fsm: Worker Ags: {}`
`2022-06-10 20:44:06.789721 WARNING vpd_fsm: ------------------------------------------------------------`
`2022-06-10 20:44:06.792763 WARNING vpd_fsm: Traceback (most recent call last):`
`  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app`
`    await utils.run_in_executor(self, init)`
`  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor`
`    response = future.result()`
`  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run`
`    result = self.fn(*self.args, **self.kwargs)`
`  File "/config/appdaemon/apps/fsm/vpd_fsm.py", line 12, in initialize`
`    Transition(next='VPD Too High', conditions=[`
`TypeError: 'module' object is not callable`
`2022-06-10 20:44:06.801721 WARNING vpd_fsm: ------------------------------------------------------------`
`2022-06-10 20:44:06.803378 INFO AppDaemon: App initialization complete`

Here is the full code of my FSM:
`	import appdaemon.plugins.hass.hassapi as hass`
`	import fsm_fsm as Fsm`
`	import fsm_state as State`
`	import fsm_transition as Transition`
`	from fsm_condition import Condition, TRUE2, Eq, Neq, LE, GE, LT, GT`

	class Fsm_vpd(hass.Hass):

	def initialize(self):
		Fsm_vpd = Fsm(self, id='Fsm_vpd', entity='input_text.t4_fsm_vpd_status', states=[
			State(id='Darkness', transitions=[
				Transition(next='VPD Too High', conditions=[
					Condition(entity='sensor.t4_rh_vpd_high', operator=Eq, operand='True')
				])
			]),
			State(id='VPD Too High', transitions=[
				Transition(next='VPD Too High', conditions=[
					Condition(entity='sensor.t4_rh_vpd_high', operator=Eq, operand='True')
				])
			])
		])


The sensor **t4_rh_vpd_high** is a template sensor whose value is _True_ or _False_. Could this be a problem?

Thanks again for your help and look forward to getting my FSM working.

**Comment by petertufvesson** [comment]
Hi Kenneth

I think the problem is here:
```
		State(id='VPD Too High', transitions=[
			Transition(next='VPD Too High', conditions=[
```
So inside a state called "VPD Too High" you should not (and cannot) have a transition to the very same state "VPD Too High"  (because this object is not fully specified yet - this is what the error is about).

Actually, there is no need to add conditions to stay in the same state, you should only add transitions leading to other states. 

Regards
/Peter

**Comment by kennethamackenzie** [comment]
Hi Peter,

Thank you so much for your help - we now a non-python developer running HA-FSM. Yeah!

Here is the full code for my simple 2 state machine:
```
import appdaemon.plugins.hass.hassapi as hass

from fsm_fsm import Fsm
from fsm_state import State
from fsm_transition import Transition
from fsm_condition import Condition, TRUE2, Eq, Neq, LE, GE, LT, GT

class Fsm_vpd(hass.Hass):

	def initialize(self):
		Fsm_vpd = Fsm(self, id='Fsm_vpd', entity='input_text.t4_fsm_vpd_status', states=[
			State(id='Darkness', transitions=[
				Transition(next='Lightness', conditions=[
					Condition(entity='switch.t4l', operand='on')
				])
			]),
			State(id='Lightness', transitions=[
				Transition(next='Darkness', conditions=[
					Condition(entity='switch.t4l', operand='off')
				])
			])
		])
```

The most important updates were to follow your import example.
Change:
```
import fsm_fsm as Fsm
import fsm_state as State
import fsm_transition as Transition
```
To:
```
from fsm_fsm import Fsm
from fsm_state import State
from fsm_transition import Transition
```

I can now watch my state machine transition states by switching the light on and off.
![Screen Shot 2022-06-11 at 12 56 52](https://user-images.githubusercontent.com/5187431/173186887-ec600c7f-136b-4db8-adaa-85e17a261b24.png)

![Screen Shot 2022-06-11 at 12 57 54](https://user-images.githubusercontent.com/5187431/173186928-cbee68cb-e0b6-4441-a237-6154d65e06d6.png)

Again Peter, thank you so much for your assistance; but, more importantly, thank you for contributing HA-FSM to the community.

Hopefully this thread will help others get started building and sharing FSM designs.

Best regards,
-Kenneth

Off to build my 10-input, 2-output, 10-state asynchronous FSM using HA entities.

**Comment by kennethamackenzie** [comment]
Closing as resolved.
